Repository Baegae/esruoc, pull requests merged in 2020-07, with the labels that each got.

#2 feat: routing-controller와 bolierplate 추가
  .eslintrc
  .gitignore
  server/.eslintrc
  server/UserController.ts
  server/index.ts
  server/package.json
  server/tsconfig.json
  yarn.lock
Labels: 🥞 backend

#11 feat(client): EditorJS를 React와 연동
  client/.eslintrc
  client/@types/editorjs.d.ts
  client/package.json
  client/pages/editor-js-test.tsx
  client/src/components/EditorJSTest/QuizBlock/index.tsx
  client/src/components/EditorJSTest/QuizBlock/plugin.tsx
  client/src/components/EditorJSTest/index.tsx
  client/tsconfig.json
  yarn.lock
Labels: 💻 frontend

#4 feat(server): Dockerfile 추가
  .dockerignore
  Dockerfile
  docker-compose-local.yaml
  run_dev.sh
Labels: 🥞 backend

#13 feat: 유저 / 강의 엔티티 추가
  server/package.json
  shared/src/entity/.gitkeep
  shared/src/entity/InProgressLecture.ts
  shared/src/entity/Lecture.ts
  shared/src/entity/Lesson.ts
  shared/src/entity/User.ts
  yarn.lock
Labels: 📚 DB

#15 fix(shared): 린트 적용 / 수정사항 반영
  shared/.eslintrc
  shared/package.json
  shared/src/entity/InProgressLecture.ts
  shared/src/entity/Lecture.ts
  shared/src/entity/Lesson.ts
  shared/src/entity/User.ts
Labels: refactoring, 📚 DB

#18 feat: Firebase 클래스가.. 커밋이 안됐넹........................................ ㅈㅅ
  server/src/database/Firebase.ts
Labels: 🥞 backend

#20 fix(server): docker-compose의 image 이름 변경
  docker-compose-local.yaml
  server/package.json
Labels: 🥞 backend

#26 feat: /lecture/[lectureId] 페이지 추가
  client/.babelrc
  client/@types/global.d.ts
  client/next.config.js
  client/package.json
  client/pages/_app.tsx
  client/pages/lecture/[lectureId].tsx
  client/public/vercel.svg
  client/src/assets/logo.svg
  client/src/assets/play.svg
  client/src/components/Layout/index.tsx
  client/src/components/Lecture/LectureInfoHeader/index.tsx
  client/src/components/Lecture/LectureInfoHeader/styles.ts
  client/src/components/Lecture/LectureLessonList/index.tsx
  client/src/components/Lecture/LectureLessonList/styles.ts
  client/src/components/common/Layout/index.tsx
  client/src/components/common/Navbar/index.tsx
  client/src/components/common/Navbar/styles.ts
  client/src/styles/normalize.ts
  client/src/styles/setGridSystem.ts
  client/tsconfig.json
  shared/src/entity/Lecture.ts
  shared/src/entity/Lesson.ts
  yarn.lock
Labels: 💻 frontend

#29 !WIP feat(client): /lecture/[lectureId]/[lessonId] 페이지 추가
  client/pages/_app.tsx
  client/pages/add-video.tsx
  client/pages/lecture/[lectureId]/[lessonId].tsx
  client/pages/lecture/[lectureId]/[lessonId]/editor.tsx
  client/public/android-chrome-192x192.png
  client/public/android-chrome-512x512.png
  client/public/apple-touch-icon.png
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon.ico
  client/public/og-image.png
  client/public/site.webmanifest
  client/src/assets/symbol.svg
  client/src/components/common/CTAButton/index.ts
  client/src/components/common/FlatButton/index.ts
  client/src/components/common/SEO/index.tsx
  client/src/components/editor-page/EditorToolBar/index.tsx
  client/src/components/editor-page/EditorToolBar/styles.ts
Labels: 💻 frontend

#31 feat(client): axios 기반 API Request 관리 기능 추가
  client/package.json
  client/src/utils/ApiRequest/index.ts
  yarn.lock
Labels: new-feature, 💻 frontend

#33 feat(client): 강의 목록 뷰 추가
  client/pages/index.tsx
  client/pages/lecture/my.tsx
  client/src/assets/add.svg
  client/src/components/Lecture/LectureCardList/LectureCardList.tsx
  client/src/components/Lecture/LectureCardList/styles.ts
  client/src/components/common/Tag/Tag.tsx
  client/src/components/common/TitleSection/index.tsx
  client/src/components/common/TitleSection/styles.ts
  shared/src/entity/Lecture.ts
Labels: new-feature, 💻 frontend

#36 feat(client): 로그인 화면 추가
  client/next.config.js
  client/pages/index.tsx
  client/src/assets/illustration.svg
  client/src/components/common/Navbar/index.tsx
  client/src/utils/ApiRequest/index.ts
  client/src/utils/Login/index.ts
  docker-compose-local.yaml
  server/src/business/UserService.ts
Labels: new-feature, 💻 frontend

#40 feat(server): LectureOutput에 차시 개수와 수강 여부 추가
  server/src/business/LectureService.ts
  server/src/controller/LectureController.ts
  shared/src/response/LectureOutput.ts
Labels: 🥞 backend

#41 feat(server): 내가 만든 강의 목록을 조회하는 API 추가
  server/src/business/LectureService.ts
  server/src/controller/LectureController.ts
Labels: 🥞 backend

#44 feat(server): 강의 세부 정보에, 내가 업로드 한 강의인지 필드 추가
  server/src/business/LectureService.ts
  server/src/controller/LectureController.ts
  shared/src/response/LectureDetailOutput.ts
Labels: 🥞 backend

#46 fix(server): 내가 만든 강의 갖고오는 로직 변경
  server/src/business/LectureService.ts
Labels: bug, 🥞 backend
